# #####################################################################
# Automatically generated by qmake (2.01a) Tue Dec 21 10:27:03 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += connection.h \
    employee.h \
    employeeform.h \
    config.h
FORMS += employeeform.ui
SOURCES += connection.cpp \
    employee.cpp \
    employeeform.cpp \
    main.cpp \
    config.cpp
